CREATE TABLE a (id INTEGER PRIMARY KEY, x INTEGER);
CREATE TABLE b (id INTEGER PRIMARY KEY, a_id INTEGER, y INTEGER);
INSERT INTO a VALUES (1, 10), (2, 20), (3, 30);
INSERT INTO b VALUES (1, 1, 100), (2, 1, 101), (3, 2, 200);
SELECT a.id, a.x, b.y FROM a INNER JOIN b ON b.a_id = a.id ORDER BY a.id, b.id;
